apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-garmin-ingest
  namespace: garmin-ingest
spec:
  instances: 1
  storage:
    storageClass: local-path
    size: 10Gi
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "128MB"
  bootstrap:
    initdb:
      database: garmin_ingest
      owner: garmin
      secret:
        name: garmin-ingest-db-credentials
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi
