apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  source:
    helm:
      values: |
        grafana:
          enabled: true
          initChownData:
            enabled: false
          admin:
            existingSecret: grafana-admin-secret
            userKey: admin-user
            passwordKey: admin-password
          persistence:
            enabled: true
            size: 5Gi
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - grafana.dev-klexify.cloud
            tls:
              - secretName: grafana-tls
                hosts:
                  - grafana.dev-klexify.cloud
        prometheus:
          prometheusSpec:
            retention: 15d
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 20Gi
        alertmanager:
          enabled: true
          alertmanagerSpec:
            configSecret: alertmanager-config
