---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-config
  namespace: monitoring
spec:
  encryptedData: {}
  template:
    metadata:
      name: alertmanager-config
      namespace: monitoring
