---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData: {}
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
