---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-minio-credentials
  namespace: monitoring
spec:
  encryptedData: {}
  template:
    metadata:
      name: loki-minio-credentials
      namespace: monitoring
