apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: garmin-ingest-auth-credentials
  namespace: garmin-ingest
spec:
  encryptedData: {}
  template:
    metadata:
      name: garmin-ingest-auth-credentials
      namespace: garmin-ingest
