apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-garmin-ingest
  namespace: garmin-ingest
spec:
  instances: 3
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
