all:
  children:
    control_plane:
      hosts:
        dev-control-plane:
          ansible_host: 87.106.11.11
    workers:
      hosts:
        dev-worker-1:
          ansible_host: 217.154.147.130
        dev-worker-2:
          ansible_host: 87.106.146.241
        dev-worker-3:
          ansible_host: 194.164.207.175
    storage_nodes:
      hosts:
        dev-storage:
          ansible_host: 87.106.90.193
    load_balancers:
      hosts:
        dev-load-balancer:
          ansible_host: 87.106.21.4
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/k8s_homepl
