apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch-domain.yaml
    target:
      kind: Application
      name: prometheus-stack
  - path: patch-loki.yaml
    target:
      kind: Application
      name: loki
