apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch-domain.yaml
    target:
      kind: Ingress
      name: argocd-ingress
  - path: patch-blackbox-probes.yaml
    target:
      kind: Probe
      name: http-endpoints
